### ISSUE TITLE
Plugin conflicts with git plugin

### ISSUE THREAD

**Issue by TheSETJ** [zdharma/fast-syntax-highlighting#153] opened 2019-08-19 10:50 UTC
I use Ubuntu bash as WSL on Windows 10 and I installed zsh + oh-my-zsh on it. There is a conflict between this plugin and default git plugin which comes with oh-my-zsh framework. When I try **gc** key sequence (aliased for `git commit -v` by git plugin), bash immediately closes. Take a look at [this StackOverflow question](https://superuser.com/questions/1472655/wsl-closes-unexpectedly-after-pressing-gc-key-sequence).

To make sure about my claim, I installed another Ubuntu bash and only installed zsh + oh-my-zsh + fast-syntax-highlighting. Then I enabled both git plugin and fast-syntax-highlighting plugin in `~/.zshrc` file and after doing `source ~/.zshrc`, I tried the key sequence and the same behavior repeated.

I didn't face any other key sequence which causes immediate close.

**Comment by mmqmzk** [comment] 2019-08-20 06:22
Same issue.

**Comment by mmqmzk** [comment] 2019-08-20 06:37
More info, press gc key sequence seems ok in ssh session on the same terminal emulator, one remote host runs ubuntu 19.04 and zsh 5.5.1, another runs Rasbain buster (Debian 10) and zsh 5.7.1, both with the same plugins enabled (git and fast-syntax-highlighting).

**Comment by TheSETJ** [comment] 2019-08-21 12:31
I found another key sequence: **git commit -**

**Comment by Azumgi** [comment] 2019-08-22 19:49
It is pretty much a duplicate of #146. Take a look at the comments. There's a working solution to prevent crashes until it gets fixed. I also listed crashing sequences and when they were introduced. There's no plugin conflict, just an alias containing crashing sequence.

**Comment by TheSETJ** [comment] 2019-08-22 21:02
@Azumgi I had crashed for **gc** sequence, it's not just **--** which is suspected in #146.

**Comment by Azumgi** [comment] 2019-08-23 11:18
@TheSETJ Disable git plugin and make any alias containing any sequence from [this comment](https://github.com/zdharma/fast-syntax-highlighting/issues/146#issuecomment-519366534) and you will get your crash all the same. It has nothing to do with git plugin itself. I don't see a point of spreading this around several issues when we can have a centralized discussion.

**Comment by Adrian-Grimm** [comment] 2019-10-14 10:51
There is a workaround like in the [two duplicate issues descriped](https://github.com/zdharma/fast-syntax-highlighting/issues?q=label%3Aduplicate+is%3Aclosed).

> Place this in your .zshrc:
> `FAST_HIGHLIGHT[chroma-git]="chroma/-ogit.ch"`

**Comment by psprint** [comment] 2019-10-21 14:03
The issue is fixed on the master branch – for the details see #146.

**Closed by psprint** 2019-10-21 14:03 UTC
Labels: bug, duplicate, upstream
