### ISSUE TITLE
'git commit -'closes the zh

### ISSUE THREAD

**Issue by billpereira** [zdharma/fast-syntax-highlighting#155] opened 2019-08-29 16:49 UTC
When we have the plugin installed with oh-my-zsh on Ubuntu running in WSL Windows 10 and we type to 'git commit -' it closes the terminal

**Comment by yous** [comment] 2019-09-01 10:23
I have the same problem. `git bisect` gives me that the cause is https://github.com/zdharma/fast-syntax-highlighting/commit/b16bf9d05da02f2498cf4144d49b243382997caf.

**Comment by yous** [comment] 2019-09-01 10:25
It seems that it's a duplicate of #146.

**Comment by PrincessRTFM** [comment] 2019-09-13 16:52
Dunno if this will be useful, but OMZSH is apparently irrelevant. I'm not using any framework at all, completely designed my environment on my own, and the same thing happens to me, also on Win10 WSL Ubuntu.

**Comment by Adrian-Grimm** [comment] 2019-09-17 11:03
Workaround could be found in #146 
Place `FAST_HIGHLIGHT[chroma-git]="chroma/-ogit.ch"` after the apply of the plugins in .zshrc.

**Closed** 2019-10-11 15:28 UTC
Labels: duplicate

**Comment by psprint** [comment] 2019-10-21 14:03
The issue is fixed on the master branch – for the details see #146.
