### ISSUE TITLE
Weird Behaviour After last pull with up Arrow Key History

### ISSUE THREAD

**Issue by iamKunal** [zdharma/fast-syntax-highlighting#26] opened 2018-06-11 20:55 UTC
There is a weird behaviour occurring when pressing the up key for previous history when the plugin is 
enabled.

Upon Pressing up only last history item shows up and cannot go further. Press Ctrl+C
Now pressing Up has more items, Press Ctrl+C
Again, more items, Press Ctrl+C
Back to single history item and loop.

Does not happen with zsh-syntax highlighting though.

[Using with oh-my-zsh]

**Comment by robobenklein** [comment] 2018-06-12 15:09
Can confirm this issue as well. It seems that going up is performing a partial history search with the current buffer as soon as it's filled instead of when editing of the line starts.

**Comment by psprint** [comment] 2018-06-12 16:30
Can I request `bindkey' output from both of you?

**Comment by robobenklein** [comment] 2018-06-12 16:40
I thought it was fixed for a moment, but after using the new shell for a few seconds (going up and down through history a few times) it gets stuck again and I have to Ctrl-C to get back to the front of the history index.

```
"^N" down-line-or-history
"^O" accept-line-and-down-history
"^P" up-line-or-history
"^R" history-search-multi-word
"^S" history-incremental-search-forward
"^X^N" infer-next-history
"^Xr" history-incremental-search-backward
"^Xs" history-incremental-search-forward
"^[ " expand-history
"^[!" expand-history
"^[," _history-complete-newer
"^[/" _history-complete-older
"^[<" beginning-of-buffer-or-history
"^[>" end-of-buffer-or-history
"^[N" history-search-forward
"^[P" history-search-backward
"^[[5~" up-line-or-history
"^[[6~" down-line-or-history
"^[[A" up-line-or-history
"^[[B" down-line-or-history
"^[n" history-search-forward
"^[p" history-search-backward
```

**Comment by iamKunal** [comment] 2018-06-12 16:50
Here it is:
```bash
"^@" autosuggest-accept
"^A" beginning-of-line
"^B" backward-char
"^D" delete-char-or-list
"^E" end-of-line
"^F" forward-char
"^G" send-break
"^H" backward-delete-char
"^I" fzf-completion
"^J" autosuggest-execute
"^K" kill-line
"^L" clear-screen
"^M" accept-line
"^N" down-line-or-history
"^O" cd-using-ranger
"^P" up-line-or-history
"^Q" push-line
"^R" history-search-multi-word
"^S" history-incremental-search-forward
"^T" transpose-chars
"^U" kill-whole-line
"^V" quoted-insert
"^W" backward-kill-word
"^X^B" vi-match-bracket
"^X^E" edit-command-line
"^X^F" vi-find-next-char
"^X^J" vi-join
"^X^K" kill-buffer
"^X^N" infer-next-history
"^X^O" overwrite-mode
"^X^R" _read_comp
"^X^U" undo
"^X^V" vi-cmd-mode
"^X^X" exchange-point-and-mark
"^X*" expand-word
"^X=" what-cursor-position
"^X?" _complete_debug
"^XC" _correct_filename
"^XG" list-expand
"^Xa" _expand_alias
"^Xc" _correct_word
"^Xd" _list_expansions
"^Xe" _expand_word
"^Xg" list-expand
"^Xh" _complete_help
"^Xm" _most_recent_file
"^Xn" _next_tags
"^Xr" history-incremental-search-backward
"^Xs" history-incremental-search-forward
"^Xt" _complete_tag
"^Xu" undo
"^X~" _bash_list-choices
"^Y" yank
"^[^D" list-choices
"^[^G" send-break
"^[^H" backward-kill-word
"^[^I" self-insert-unmeta
"^[^J" self-insert-unmeta
"^[^L" clear-screen
"^[^M" self-insert-unmeta
"^[^_" copy-prev-word
"^[ " expand-history
"^[!" expand-history
"^[\"" quote-region
"^[\$" spell-word
"^['" quote-line
"^[," _history-complete-newer
"^[-" neg-argument
"^[." insert-last-word
"^[/" _history-complete-older
"^[0" digit-argument
"^[1" digit-argument
"^[2" digit-argument
"^[3" digit-argument
"^[4" digit-argument
"^[5" digit-argument
"^[6" digit-argument
"^[7" digit-argument
"^[8" digit-argument
"^[9" digit-argument
"^[<" beginning-of-buffer-or-history
"^[>" end-of-buffer-or-history
"^[?" which-command
"^[A" accept-and-hold
"^[B" backward-word
"^[C" capitalize-word
"^[D" kill-word
"^[F" forward-word
"^[G" get-line
"^[H" run-help
"^[L" down-case-word
"^[N" history-search-forward
"^[OA" up-line-or-beginning-search
"^[OB" down-line-or-beginning-search
"^[OC" forward-char
"^[OD" backward-char
"^[OF" end-of-line
"^[OH" beginning-of-line
"^[P" history-search-backward
"^[Q" push-line
"^[S" spell-word
"^[T" transpose-words
"^[U" up-case-word
"^[W" copy-region-as-kill
"^[[1;5C" forward-word
"^[[1;5D" backward-word
"^[[200~" bracketed-paste
"^[[2~" overwrite-mode
"^[[3~" delete-char
"^[[5~" up-line-or-history
"^[[6~" down-line-or-history
"^[[A" up-line-or-history
"^[[B" down-line-or-history
"^[[C" forward-char
"^[[D" backward-char
"^[[Z" reverse-menu-complete
"^[_" insert-last-word
"^[a" accept-and-hold
"^[b" backward-word
"^[c" capitalize-word
"^[d" kill-word
"^[f" forward-word
"^[g" get-line
"^[h" run-help
"^[l" "ls^J"
"^[m" copy-prev-shell-word
"^[n" history-search-forward
"^[p" history-search-backward
"^[q" push-line
"^[s" spell-word
"^[t" transpose-words
"^[u" up-case-word
"^[w" kill-region
"^[x" execute-named-cmd
"^[y" yank-pop
"^[z" execute-last-named-cmd
"^[|" vi-goto-column
"^[~" _bash_complete-word
"^[^?" backward-kill-word
"^_" undo
" " magic-space
"!"-"~" self-insert
"^?" backward-delete-char
"\M-^@"-"\M-^?" self-insert
```

**Comment by NemesisRE** [comment] 2018-06-14 16:38
I have the same but I noticed that only the first item is the original history every item after that is only something that contains the first. For example last item was "vim" and the next in history would be "nano" but instead it is "vim .vimrc" from two days ago. I think it tries to complete the command.

**Comment by robobenklein** [comment] 2018-06-14 17:59
Ctrl-R for multi-word history search has been fine for me. (And I've been appreciating it much more while this issue is still going.) I've only been having problems with the up/down arrow mapping to history-partial-search.

**Comment by psprint** [comment] 2018-06-15 06:42
I've disabled `vim` chroma (it needs development anyway), does it help?

**Comment by NemesisRE** [comment] 2018-06-15 09:38
I'm afraid not.

**Comment by psprint** [comment] 2018-06-15 14:47
Great, thanks, I've forgot about async commit. It would be good if I could reproduce this.

**Comment by psprint** [comment] 2018-06-15 15:30
So the idea is: when browsing history with up & down keys, multiple background processes are spawned because each complete line invokes potentially multiple path-checks. So 5 times up/down, means say 10 background processes, or more. I've added explicit ending of those processes, following what zsh-autosuggestion does. Did it help?

**Comment by robobenklein** [comment] 2018-06-15 15:47
Behavior seems to have changed.

I can go up through a number of commands until I reach one that has a path in it.

For example, I can scroll through `gca,gst,gd,docker run ...,` but then upon coming to `cd some/path` it seems to get hung directly after, and from that point it treats the history search as looking for history beginning with that partial search.

**Comment by robobenklein** [comment] 2018-06-15 15:52
I recorded an example.

Here I am trying to go up and down through history (up/down arrows) until it stops on some history item, where I can no longer move through history. At that point I ctrl-c and try again a few times.

https://asciinema.org/a/Aef42KEMcFSVU427sHfMXeEy1

Note for that last one that got stuck on `antigen update` I suspect got frozen there because the command before it had a path and the async path check came back while the current command was displayed. Not sure if that's exactly what's happening, but seems plausible.

**Comment by psprint** [comment] 2018-06-15 15:55
I've added one more commit, could you check? What is $ZSH_VERSION?

**Comment by robobenklein** [comment] 2018-06-15 16:27
I'm on zsh 5.4.2 (x86_64-ubuntu-linux-gnu)

Going through history again, the problem seems to come up every time after I scroll past a `cd` command, even one that was blank with no arguments. After going past the `cd` history item,

**Comment by psprint** [comment] 2018-06-15 16:31
The message from you got interrupted.

I've applied one different patch, maybe it's better now?

**Comment by robobenklein** [comment] 2018-06-15 16:36
I do push a docker image of my configs that has the same problem, I can reproduce on `robobenklein/home:latest` with just a few commands:

```
robo@4ebc60156c89 ~> echo hello
hello
robo@4ebc60156c89 ~> cd code/configs
robo@4ebc60156c89 ~/c/configs> cd
robo@4ebc60156c89 ~> echo hi 
hi
robo@4ebc60156c89 ~> echo hello # went back in history, got stuck here, cannot move to more recent history
robo@4ebc60156c89 ~>
```

**Comment by psprint** [comment] 2018-06-15 18:15
I don't know docker, but managed to invoke `docker run ...` on the ID that you provided. I get, after image has been downloaded:

PermissionError: [Errno 13] Permission denied: '/etc/container_environment'

**Comment by robobenklein** [comment] 2018-06-15 18:33
Sorry about the trouble, this will bring you right into a zsh session: `docker run --rm -t -i robobenklein/home:latest zsh -l`

**Comment by psprint** [comment] 2018-06-15 21:17
Ok it works and reproduces. Could gdb package be added? I would attach to Zsh when the blockage is active and see where it hangs.

**Comment by robobenklein** [comment] 2018-06-16 01:03
I may be a poor college student, but the time your work has saved me has definitely been worth something.

I've updated the docker image. I look forward to being your first patreon supporter!

**Comment by psprint** [comment] 2018-06-16 05:52
> If this is the issue, a patch upstream might be helpful.

You mean to Zshell?

In general the explanation you gave seems to apply. On the docker image @robobenklein provided, when I remap cursor keys from `up-line-or-beginning-search` to `up-line-or-history`, etc., then no stall occurs.

What's interesting is that `cat -v` was showing different codes that ones actually used for the `*beginning-search`, yet when I rebind the later, I get a reaction.

**Comment by ericfreese** [comment] 2018-06-16 05:54
> You mean to Zshell?

Yes, I suppose I should specify :) I was imagining rewriting `up/down-line-or-beginning-search` widgets to somehow not use `LASTWIDGET`.

**Comment by psprint** [comment] 2018-06-16 06:08
On 16 June 2018 at 03:03, Ben Klein <notifications@github.com> wrote:

> I may be a poor college student, but the time your work has saved me has
> definitely been worth something.
>
> I've updated the docker image. I look forward to being your first patreon
> supporter!
>
Indeed my patreon page reports first patron. Thanks!

**Comment by psprint** [comment] 2018-06-16 14:27
Added quick fix after checking that `$LASTWIDGET` is readonly and cannot be manipulated. It helps on the docker image. Is it ok now? The patch skips async-path checking if `$LASTWIDGET` is `*-or-beginning-search`. When I'll be ready for more coding, I might code that path will be checked in this case, although not asynchronously.

**Comment by popstas** [comment] 2018-06-17 00:44
@psprint, thank you! It helps me. I'm using fast-syntax-highlighting with [ansible-role-zsh](https://github.com/viasite-ansible/ansible-role-zsh) and has trouble with history some last days.

**Comment by iamKunal** [comment] 2018-06-17 21:20
Sorry for the late reply, but I just checked again. It works now with the latest commit!

**Comment by NemesisRE** [comment] 2018-06-18 09:06
Works like a charm thank you :)

**Closed** 2018-06-18 22:44 UTC
