### ISSUE TITLE
alias chroma not working for single letter aliases

### ISSUE THREAD

**Issue by plexigras** [zdharma/fast-syntax-highlighting#47] opened 2018-07-21 20:45 UTC
for example the git chroma does work for `gc -m '...'` but not for `g commit -m '...'` where `g` is aliased to `git` and `gc` to `git commit`

and `echo $aliases[g]` prints `git`

and the issue is not specific to the git chroma nor the letter g nor it being aliased to git

**Comment by psprint** [comment] 2018-07-22 06:42
The cause was that alias expanded to single word. It should be fixed now.

**Closed** 2018-07-22 09:13 UTC
