### ISSUE TITLE
zsh segmentation fault

### ISSUE THREAD

**Issue by HaleTom** [zdharma/fast-syntax-highlighting#108] opened 2019-02-24 03:36 UTC
I've discovered that `zsh` causes a segmentation fault when used with this plugin as follows:
```
% zsh -df
svelte% git clone --quiet --depth 1 --single-branch --branch master https://github.com/zdharma/fast-syntax-highlighting.git                                                                                       
svelte% source fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh
svelte% zsh -c '"'"
dquote> zsh: segmentation fault (core dumped)  zsh -df
```

Note: You need to press <kbd>Enter</kbd> at the `dquote>` prompt.

I suspect this is a `zsh` codebase issue, but I'm following due process and reporting it here first.

**Comment by psprint** [comment] 2019-02-27 22:51
It's little weird that It does reproduce on apple provided zsh-5.3, but not on own-compiled zsh (various versions, including the 5.3). Could you confirm that on hand-build Zsh it also dosen't reproduce for you?

**Comment by HaleTom** [comment] 2019-03-07 06:04
I'm sorry, I should have provided this detail already:

```
% zsh --version; uname -a                                  
zsh 5.7.1 (x86_64-pc-linux-gnu)
Linux svelte 4.19.20-1-MANJARO #1 SMP PREEMPT Wed Feb 6 21:33:34 UTC 2019 x86_64 GNU/Linux
```

Given it segfaults both on a very recent `zsh`, as well as Apple's `zsh 5.3`, it seems like it's a `zsh` problem that's been around for some time.

Are you interested to dig into exactly what code is causing the segfault, or should I raise it further upstream?

**Comment by psprint** [comment] 2019-03-08 23:06
@HaleTom I might at least run gdb / lldb if I manage to have it reproducing on a hand built Zsh (that's why I've asked you for the check), but I think that you should raise this further. I wonder if it reproduces with zsh-syntax-highlighting too, I'll check that tomorrow

**Comment by psprint** [comment] 2019-03-13 05:05
Too bad that it doesn't reproduce on zsh-syntax-highlighting (i've just checked)

**Comment by HaleTom** [comment] 2019-03-13 08:54
@psprint Personally, I'm glad you're stretching `zsh` more than the basic syntax highlighting (I love your plugin), but I do admit the issue would be easier to track down with a larger user base.

I'm willing to build `zsh` myself if it would help, but am a padawan learner when it comes to `gdb`.

If I'm able to reproduce on a self-built version, how will this help out (apart from having a third confirmed datapoint)?

**Comment by psprint** [comment] 2019-03-14 03:20
> If I'm able to reproduce on a self-built version, how will this help out (apart from having a third confirmed datapoint)?

I would then know with a fair-probability, that my hand-built zshells should also reproduce the problem, and I would then experiment with them (to make them reproduce the problem)

**Comment by HaleTom** [comment] 2019-03-14 09:06
I was able to reproduce when buiding with the following (taken from Arch Linux's `PKGBUILD`):

```
	./configure --prefix=/usr \
		--docdir=/usr/share/doc/zsh \
		--htmldir=/usr/share/doc/zsh/html \
		--enable-etcdir=/etc/zsh \
		--enable-zshenv=/etc/zsh/zshenv \
		--enable-zlogin=/etc/zsh/zlogin \
		--enable-zlogout=/etc/zsh/zlogout \
		--enable-zprofile=/etc/zsh/zprofile \
		--enable-zshrc=/etc/zsh/zshrc \
		--enable-maildir-support \
		--with-term-lib='ncursesw' \
		--enable-multibyte \
		--enable-function-subdirs \
		--enable-fndir=/usr/share/zsh/functions \
		--enable-scriptdir=/usr/share/zsh/scripts \
		--with-tcsetpgrp \
		--enable-pcre \
		--enable-cap \
		--enable-zsh-secure-free
	make
```

Let me know if you need anything else.

**Comment by HaleTom** [comment] 2019-03-24 03:37
Were you able to reproduce with the above config?

**Comment by psprint** [comment] 2019-03-24 11:17
I'm in hospital currently, sorry. I should be back in 7 days

Niedz., 24.03.2019, 04:37 użytkownik Tom Hale <notifications@github.com>
napisał:

**Comment by HaleTom** [comment] 2019-04-01 08:43
Really sorry to hear that.  I hope everything has turned out ok.  Take the time you need for yourself.

**Comment by psprint** [comment] 2019-04-04 10:58
Thanks!

Pon., 1.04.2019, 10:43 użytkownik Tom Hale <notifications@github.com>
napisał:

**Comment by benjaminbauer** [comment] 2019-06-25 15:21
Hi @HaleTom @psprint ,

I face a seg fault too, when

1. I have this alias `alias gup='git pull --rebase'`
2. And I type `gup` in the zsh with zdharma/fast-syntax-highlighting active
3. Then: zsh crashes with a seg fault as soon as I enter the last char `p`

This behavior does not occur when

1. the plugin is not loaded
2. or I reduce the alias to `git pull`

zsh: `5.7.1 (x86_64-pc-linux-gnu)`
zdharma/fast-syntax-highlighting: cf67edef842130879c11813d0f6752611812ea05

**Comment by psprint** [comment] 2019-06-25 18:29
Doesn't happen here, also on 5.7.1, and also newest FSH. Which OS? Could you provide a backtrace? To have it, you can start zsh inside zsh, then enter command `ulimit -c unlimited`, then do the crash (i.e. enter `gup`). A core should be dumped, either in current directory on in /cores (OS X). Then enter `lldb -c /cores/core.XYZ` on OSX or AFAIR `gdb -c core.XYZ` on linux. Then, after the debugger starts, enter `bt`, the output is the backtrace of which I'm asking.

PS. Does the problem occur when you enter: `git pull --rebase`?

**Comment by benjaminbauer** [comment] 2019-06-26 07:38
>  Which OS? 
Arch Linux in Windows 10 WSL. I could _not_ reproduce the behavior at home on a native Arch.
> PS. Does the problem occur when you enter: git pull --rebase?
Yes, when I enter `git pull -`, the crash occurs on the `-`
> Could you provide a backtrace?
Ran into a roadblock on WSL https://github.com/microsoft/WSL/issues/1262 😞

**Comment by psprint** [comment] 2019-06-26 11:00
@benjaminbauer: You could use the old Git chroma for now, by issuing:

```zsh
typeset -gA FAST_HIGHLIGHT # only needed when assigning before loading the plugin
FAST_HIGHLIGHT[chroma-git]="chroma/-ogit.ch"
```

Despite it is technically old, it's quite fresh end up to date.

**Comment by Sharparam** [comment] 2019-06-27 15:27
I have the same problem as @benjaminbauer with Ubuntu 18.04 on WSL with `alias gfr='git pull --rebase'` provided by prezto's git modules.

.zshrc and the output I'm able to get from `gdb` in [this gist](https://gist.github.com/Sharparam/1055538c4444cb8f16dd741e52a633b8), along with system information.

**Comment by HaleTom** [comment] 2019-06-29 11:03
As this has been open for 4 months now, I intend to raise it upstream with `zsh` within 2 weeks unless I hear otherwise.

**Comment by looselyrigorous** [comment] 2019-07-12 21:15
Hello, I'm also having segfaults but with a different command. I'm not entirely sure if it's related to this but I thought I'd post here first.

```
~
❯ zsh --version
zsh 5.7.1 (x86_64-pc-linux-gnu)

~
❯ zsh -df
sakuya% source "$HOME/.zsh/.zplugin/bin/zplugin.zsh"
sakuya% zplugin load zdharma/fast-syntax-highlighting
sakuya% a `
bquote> zsh: segmentation fault (core dumped)  zsh -df
```

It crashes after printing `bquote>`.

**Comment by psprint** [comment] 2019-07-13 01:29
I confirm that this reproduces. I'm preparing a report to the upstream. Would be good, however, to find a workaround..

**Comment by psprint** [comment] 2019-07-13 04:17
The issue with `a \`\n` is fixed :) Thanks!

**Comment by HaleTom** [comment] 2019-07-14 04:55
Hi @psprint, I hope your health has significantly improved.

My 2 week timer went off, but I see that you're working on a report yourself.

I'll raise it myself in 2 weeks if you don't report here that you've reported it, how does that sound?

**Comment by psprint** [comment] 2019-07-14 20:55
Hello @HaleTom. Yeah I'm fully healthy now, thanks!

(**UPDATE**: The issue has been solved, look at bottom.) As for the report, the problem is that I cannot obtain a backtrace. Your issue is different from the other reports (well, maybe not from the "--"-related reports, but that doesn't reproduce to me at all) so I'm stuck at the "occurs only at Apple zsh binary" obstacle. But I see that you've reproduced on self-built zshell. That's great! Just be sure to prepend the `./configure` with `CFLAGS=`: `CFLAGS="-Wall -O0 -g" ./configure ...". After issuing make clean, you can then issue `make` to built non-optimized zsh with debugging information compiled in. If you've maybe deleted your previous compilation of Zsh, then here's a zplugin snippet just to help you out:

```zsh
zplugin ice as"command" \
    atclone"./.preconfig; CFLAGS=\"-g -Wall -O0\" ./configure" \
    atpull"%atclone" make"all install"
zplugin light zsh-users/zsh
```
Warning: it will install the zsh. To obtain the backtrace:
- run the self-built zsh from within zshell, by first issuing `ulimit -c unlimited` in the original zshell, and then by issuing `/usr/local/bin/zsh -l -i`,
- issue the `ulimit -c unlimited` command again in the new zsh,
- then do the `zsh -c '"'"` step to trigger the crash,
- this should generate a core; on OSX it can be a large one and generating can take up a few minutes,
- on OS X, the core will be in `/cores/core.{PID}`, on Linux in the current directory in file `core.{PID}`,
- then run: `lldb -c /cores/core.{PID}` or `gdb -c core.{PID}`,
- after the debugger starts, enter `bt`
```

When writing this, I've realized that the issue has the same cause as the @looselyrigorous issue. So the above steps aren't needed! However I'll left them as they're might help someone else reporting a segfault in the FSH.

**Closed** 2019-12-30 01:47 UTC
Labels: bug, problem, unknown, upstream
